### PR TITLE
[ARC] [libgloss] Drop dwuart support

### PR DESCRIPTION
**Pull request by VVIsaev**
Metaware hostlink should be used instead of dwuart.

### CODE REVIEW

**Comment by claziss** [comment]
Sorry we cannot do that. We need to place something in place. Removing it without providing an free alternative is not an option.

**Comment by anthony-kolesov** [comment]
I don't see how hostlink can replace UART. Hostlink/semihosting solutions by their nature require additional host and a program that services hostlink requests. UART is a standalone solution that can be run on a board without any external hosts and debuggers - hostlink can't address those usecases.

**Comment by abrodkin** [comment]
@claziss given the mess it is now (IRQ support, board specs for just pretty much obsolete EMSK platform), meaningless dependency on EM cores in particular (well, because the one and only driver was to run smoke tests on a real board, back in the day it was EMSK.

Now if we want to have a similar functionality for real boards, we need to implement something as simple as this: https://www.sourceware.org/git/?p=newlib-cygwin.git;a=blob;f=libgloss/or1k/or1k_uart.c.

And still implementation on that simple UART driver as pointed to above needs to have this massive clean-up as a per-requisite.

**Comment by claziss** [comment]
@abrodkin I do use EMSK, UART is provided in all our SDK platforms. Please provide a proper support, and then you may remove what we have. Thanks

**Pull request closed without merging**
